version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

  app:
    build: .
    ports: 
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - db

volumes:
  db-data: